//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AK_Website_Project.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int ItemId { get; set; }
        public string Name { get; set; }
        public int SubCategoryId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public bool IsCommentsAllowed { get; set; }
        public int QualityLevelId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual QualityLevel QualityLevel { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
